# -*- coding: utf-8 -*-
"""AI Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P9bJQhlrWtMRS2MfN0EoSHn5X0EItX1R
"""

pip install pandas scikit-learn

import pandas as pd
from google.colab import files
import os


if not os.path.exists('logs.csv'):
    print("logs.csv not found. Please upload the file.")
    uploaded = files.upload()
    for fn in uploaded.keys():
        print('User uploaded file "{name}" with length {length} bytes'.format(name=fn, length=len(uploaded[fn])))

df = pd.read_csv("logs.csv")

print(" Logs Loaded Successfully")
print(df.head())

# Compress logs by grouping similar events
compressed_logs = df.groupby(["user","action","status"]).size().reset_index(name="count")

print(" Original Log Size:", len(df))
print(" Compressed Log Size:", len(compressed_logs))

print("\nCompressed Logs Preview:")
print(compressed_logs.head())

# Convert categorical data to numbers
df_encoded = df.copy()

df_encoded["user"] = df_encoded["user"].astype("category").cat.codes
df_encoded["ip"] = df_encoded["ip"].astype("category").cat.codes
df_encoded["action"] = df_encoded["action"].astype("category").cat.codes
df_encoded["status"] = df_encoded["status"].astype("category").cat.codes

print(" Logs Encoded for AI")
df_encoded.head()

from sklearn.ensemble import IsolationForest

# Select features
features = df_encoded[["time","user","ip","action","status"]]

# Train anomaly detection model
model = IsolationForest(contamination=0.15, random_state=42)
df_encoded["anomaly"] = model.fit_predict(features)

print(" Threat Detection Completed")
df_encoded.head()

# Find suspicious activities
alerts = df[df_encoded["anomaly"] == -1]

print(" ALERTS DETECTED:")
print(alerts)

import matplotlib.pyplot as plt

# Count anomalies
counts = df_encoded["anomaly"].value_counts()

plt.bar(counts.index.astype(str), counts.values)
plt.title("Threat Detection Results")
plt.xlabel("Anomaly (-1 = Threat, 1 = Normal)")
plt.ylabel("Number of Events")
plt.show()

import pandas as pd
from sklearn.ensemble import IsolationForest

class SecurityMonitoringAgent:

    def __init__(self):
        print("\n" + "="*60)
        print("      SECURITY MONITORING AI AGENT INITIALIZED")
        print("="*60)

    def load_logs(self, file):
        print("\n[1] Loading Security Logs...")
        data = pd.read_csv(file)
        print(f"   ✔ {len(data)} logs loaded successfully.")
        return data

    def compress_logs(self, data):
        print("\n[2] Performing Log Compression (ScaleDown)...")
        before = len(data)
        compressed = data.drop_duplicates()
        after = len(compressed)
        print(f"   ✔ Logs reduced from {before} → {after}")
        return compressed

    def detect_threats(self, data):
        print("\n[3] Running AI-Based Threat Detection...")

        # Encode categorical features for the model
        df_encoded_local = data.copy()
        for col in ["user", "ip", "action", "status"]:
            if col in df_encoded_local.columns:
                df_encoded_local[col] = df_encoded_local[col].astype("category").cat.codes

        # Select features present in the dataframe
        features_to_use = [col for col in ["time", "user", "ip", "action", "status"] if col in df_encoded_local.columns]
        if not features_to_use:
            raise ValueError("No suitable features found for anomaly detection. Ensure 'time', 'user', 'ip', 'action', or 'status' columns exist.")

        model = IsolationForest(contamination=0.1, random_state=42)
        df_encoded_local["anomaly"] = model.fit_predict(df_encoded_local[features_to_use])
        data["anomaly"] = df_encoded_local["anomaly"] # Add anomaly results back to original data
        print("   ✔ Anomaly detection completed.")
        return data

    def respond(self, data):
        print("\n[4] Generating Security Alerts...")
        threats = data[data["anomaly"] == -1]

        if threats.empty:
            print("   ✔ System Secure. No threats detected.")
        else:
            print(f"   ⚠ {len(threats)} Threat(s) Detected:")
            print("   Suspicious IP Addresses:")
            print(threats["ip"].unique())

    def run(self, file):
        logs = self.load_logs(file)
        logs = self.compress_logs(logs)
        results = self.detect_threats(logs)
        self.respond(results)

        print("\n" + "="*60)
        print("      AI AGENT EXECUTION COMPLETED SUCCESSFULLY")
        print("="*60)

agent = SecurityMonitoringAgent()
agent.run("logs.csv")

print(f"System Risk Level: {len(alerts)} anomaly events detected.")